### ISSUE TITLE
ability to get the original error and body?

### ISSUE THREAD

**Issue by contra** [overlookmotel/got-resume#16]
currently got-resume obscures the original error (you'll just see that it ran out of attempts), and also obscures the response that caused the error in case of a fatal error. this makes it hard to debug.

solution could be as simple as:
- adding `.original = this.err` to any errors before they get emitted
- adding `this.err.res = res` to L128 of transfer.js (res is the third argument of the error response)

This allows you to do this:

```js
    .once('error', async (err) => {
      const { original, res } = req.transfer

      // buffer the error body to see what happened
      if (res) text = await collect(res, { maxBuffer: sizeLimit })
      console.log(original, text)
    })
```

if interested i will send a PR, lmk.

**Comment by overlookmotel** [comment]
Sorry it's taken me 2 years to reply to this! I missed it completely.

Problem is that because got-resume retries many times in the case of an error, it's hard to say which of the (by default 10) errors is the one which caused the ultimate failure. So question becomes which "original" error?

To get info on every request failure, I'd suggest using the `log` option which will be called with every response error, as well as various other useful information (what size chunks were transferred in each request etc).
